# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationEngineStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/sew.simulation.SimulationEngine/StartSession',
                request_serializer=simulation__pb2.StartRequest.SerializeToString,
                response_deserializer=simulation__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/sew.simulation.SimulationEngine/Step',
                request_serializer=simulation__pb2.StepRequest.SerializeToString,
                response_deserializer=simulation__pb2.StepResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/sew.simulation.SimulationEngine/DestroySession',
                request_serializer=simulation__pb2.DestroyRequest.SerializeToString,
                response_deserializer=simulation__pb2.DestroyResponse.FromString,
                _registered_method=True)


class SimulationEngineServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def StartSession(self, request, context):
        """Allocate a new session: build world0, index agents, set block-time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Execute one event against the session's canonical world state.
        Returns the updated world_view, a full trace entry, and halted flag.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Destroy a session and free its resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=simulation__pb2.StartRequest.FromString,
                    response_serializer=simulation__pb2.StartResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=simulation__pb2.StepRequest.FromString,
                    response_serializer=simulation__pb2.StepResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=simulation__pb2.DestroyRequest.FromString,
                    response_serializer=simulation__pb2.DestroyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sew.simulation.SimulationEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sew.simulation.SimulationEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationEngine(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sew.simulation.SimulationEngine/StartSession',
            simulation__pb2.StartRequest.SerializeToString,
            simulation__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sew.simulation.SimulationEngine/Step',
            simulation__pb2.StepRequest.SerializeToString,
            simulation__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sew.simulation.SimulationEngine/DestroySession',
            simulation__pb2.DestroyRequest.SerializeToString,
            simulation__pb2.DestroyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
